- name: Create GitHub SSH Key Credential
  awx.awx.credential:
    name: GitHub SSH Key
    organization: Default
    state: present
    credential_type: Source Control
    inputs:
      username: "{{ GIT_USERNAME }}"
      ssh_key_data: "{{ GIT_PRIVATE_KEY }}"
      ssh_key_unlock: "{{ GIT_PRIVATE_KEY_PHRASE }}"
  environment:
    TOWER_HOST: "{{ TOWER_HOST }}"
    TOWER_USERNAME: "{{ TOWER_USERNAME }}"
    TOWER_PASSWORD: "{{ TOWER_PASSWORD }}"

- name: Create Credential {{ CREDENTIAL_GET_TRANSACTIONS_01 }}
  awx.awx.credential:
    name: "{{ CREDENTIAL_GET_TRANSACTIONS_01 }}"
    organization: Default
    state: present
    credential_type: "{{ CRENDENTIAL_TYPE_GET_TRANSACTIONS }}"
    inputs:
      user: "{{ B_USERNAME_01 }}"
      password: "{{ B_PASSWORD_01 }}"
      login_url: "{{ LOGIN_URL }}"
      encryption_key_id: "{{ ENCRYPTION_KEY_ID }}"
      api: "{{ BASE_API }}"
  environment:
    TOWER_HOST: "{{ TOWER_HOST }}"
    TOWER_USERNAME: "{{ TOWER_USERNAME }}"
    TOWER_PASSWORD: "{{ TOWER_PASSWORD }}"

- name: Create Credential {{ CREDENTIAL_GET_TRANSACTIONS_02 }}
  awx.awx.credential:
    name: "{{ CREDENTIAL_GET_TRANSACTIONS_02 }}"
    organization: Default
    state: present
    credential_type: "{{ CRENDENTIAL_TYPE_GET_TRANSACTIONS }}"
    inputs:
      user: "{{ B_USERNAME_02 }}"
      password: "{{ B_PASSWORD_02 }}"
      login_url: "{{ LOGIN_URL }}"
      encryption_key_id: "{{ ENCRYPTION_KEY_ID }}"
      api: "{{ BASE_API }}"
  environment:
    TOWER_HOST: "{{ TOWER_HOST }}"
    TOWER_USERNAME: "{{ TOWER_USERNAME }}"
    TOWER_PASSWORD: "{{ TOWER_PASSWORD }}"

- name: Create Postgres Credential
  awx.awx.credential:
    name: Postgres
    organization: Default
    state: present
    credential_type: Postgres
    inputs:
      host: "{{ POSTGRES_HOST }}"
      user: "{{ POSTGRES_USERNAME }}"
      password: "{{ POSTGRES_PASSWORD }}"
      database_name: "{{ POSTGRES_DB_NAME }}"
  environment:
    TOWER_HOST: "{{ TOWER_HOST }}"
    TOWER_USERNAME: "{{ TOWER_USERNAME }}"
    TOWER_PASSWORD: "{{ TOWER_PASSWORD }}"

- name: Create credential {{ CREDENTIAL_SPLUNK_HEC_01 }}
  awx.awx.credential:
    name: "{{ CREDENTIAL_SPLUNK_HEC_01 }}"
    organization: Default
    state: present
    credential_type: Splunk HEC
    inputs:
      splunk_url: "{{ SPLUNK_URL }}"
      splunk_header: "{{ SPLUNK_HEADER }}"
  environment:
    TOWER_HOST: "{{ TOWER_HOST }}"
    TOWER_USERNAME: "{{ TOWER_USERNAME }}"
    TOWER_PASSWORD: "{{ TOWER_PASSWORD }}"

- name: Create credential {{ CREDENTIAL_SPLUNK_HEC_02 }}
  awx.awx.credential:
    name: "{{ CREDENTIAL_SPLUNK_HEC_02 }}"
    organization: Default
    state: present
    credential_type: Splunk HEC
    inputs:
      splunk_url: "{{ SPLUNK_URL }}"
      splunk_header: "{{ SPLUNK_HEADER_02 }}"
  environment:
    TOWER_HOST: "{{ TOWER_HOST }}"
    TOWER_USERNAME: "{{ TOWER_USERNAME }}"
    TOWER_PASSWORD: "{{ TOWER_PASSWORD }}"
